<?php
$fruits_and_vegetables = [
    "apple",
    "banana",
    "orange",
    "strawberry",
    "grape",
    "mango",
    "blueberry",
    "raspberry",
    "watermelon",
    "cherry",
    "pear",
    "lemon",
    "lime",
    "kiwi",
    "pineapple",
    "melon",
    "coconut",
    "pomegranate",
    "peach",
    "apricot",
    "plum",
    "grapefruit",
    "blackberry",
    "papaya",
    "guava",
    "lychee",
    "tangerine",
    "fig",
    "date",
    "passion fruit",
    "star fruit",
    "persimmon",
    "dragon fruit",
    "jackfruit",
    "durian",
    "red currant",
    "gooseberry",
    "elderberry",
    "cranberry",
    "mulberry",
    "cucumber",
    "tomato",
    "carrot",
    "broccoli",
    "onion",
    "garlic",
    "cabbage",
    "pea",
    "zucchini",
    "corn",
    "pepper",
    "lettuce",
    "spinach",
    "mushroom",
    "potato",
    "sweet potato",
    "eggplant",
    "asparagus",
    "cauliflower",
    "celery",
    "kale",
    "green bean",
    "scallion",
    "shallot",
    "ginger",
    "radish",
    "pumpkin",
    "squash",
    "artichoke",
    "leek",
    "chili pepper",
    "bell pepper",
    "jalapeno",
    "habanero",
    "fennel",
    "beet",
    "rutabaga",
    "turnip",
    "horseradish",
    "yam",
    "bok choy",
    "parsnip",
    "watercress",
    "bamboo shoot",
    "endive",
    "arugula",
    "chicory",
    "kohlrabi",
    "collard greens",
    "swiss chard",
    "mustard greens",
    "Brussels sprout",
    "romaine lettuce",
    "okra",
    "avocado"
];
?>
